In [1]:
import numpy as np

In [2]:
print
(np.__version__)

'2.0.2'

In [3]:
py_list = [1,2,3,4,5]

np_array = np.array([1,2,3,4,5])

print(py_list)
print(np_array)
print(type(py_list), type(np_array))

[1, 2, 3, 4, 5]
[1 2 3 4 5]
<class 'list'> <class 'numpy.ndarray'>


In [4]:
print(py_list *2)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [5]:
print(np_array *2)

[ 2  4  6  8 10]


In [6]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])
print(a + b)
print(a * b)

[11 22 33]
[10 40 90]


In [7]:
a = np.array([1, 2, 3])
b = 10
print(a + b)

[11 12 13]


In [8]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
row = np.array([10, 20, 30])
print(matrix + row)

[[11 22 33]
 [14 25 36]]


In [9]:
a = np.array([10, 20, 30, 40, 50])

print(a[0])
print(a[-1])
print(a[1:4])

10
50
[20 30 40]


In [10]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print(matrix[0])
print(matrix[0][1])
print(matrix[0, 1])

[1 2 3]
2
2


In [11]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print(matrix[:2, 1:])

[[2 3]
 [5 6]]


In [12]:
print(matrix[0:,2:])

[[3]
 [6]
 [9]]


In [13]:
a = np.array([10, 25, 3, 47, 18, 32])
mask = a > 20
print(mask)
print(a[mask])

[False  True False  True False  True]
[25 47 32]


In [16]:
a = np.array([10, 25, 3, 47, 18, 32])
a[a>20] = 0
print(a)

[10  0  3  0 18  0]


In [17]:
a = np.array([1, 2, 3, 4, 5, 6])
b = np.array([[1, 2, 3], [4, 5, 6]])
c = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print(a.shape)
print(b.shape)
print(c.shape)

(6,)
(2, 3)
(2, 2, 2)


In [18]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a.shape)
print(a.ndim)

(6,)
1


In [19]:
row_vec = np.array([[1, 2, 3, 4, 5, 6]])      # 대괄호 두 겹!
col_vec = np.array([[1], [2], [3], [4], [5], [6]])

print(row_vec.shape)
print(col_vec.shape)

(1, 6)
(6, 1)


In [20]:
print(type((3)))     # 이건 뭘까요?
print(type((3,)))    # 이건 뭘까요?

<class 'int'>
<class 'tuple'>


In [21]:
a = np.arange(12)
print(a)
print(a.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)


In [22]:
b = a.reshape(3, 4)
print(b)
print(b.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)


In [23]:
a = np.arange(12)
print(a.reshape(3, -1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [24]:
a = np.arange(12)
print(a.reshape(3, -1))
print(a.reshape(-1, 4))
print(a.reshape(2, 2, -1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [25]:
a = np.arange(12)
print(a.reshape(-1, -1))

ValueError: can only specify one unknown dimension

In [26]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])

print(matrix.sum())
print(matrix.sum(axis=0))
print(matrix.sum(axis=1))

21
[5 7 9]
[ 6 15]


In [27]:
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

print(A * B)
print(A @ B)

[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


In [28]:
A = np.array([[2, 0],
              [0, 2]])
v = np.array([3, 5])

print(A @ v)

[ 6 10]


In [31]:
R = np.array([[0,-1],
              [1,0]])  # 90도 회전 행렬을 직접 적어보세요
v = np.array([1, 0])

print(R @ v)

[0 1]
